version: '3'
# https://github.com/kylemanna/docker-openvpn/blob/master/docs/docker-compose.md

services:
   openvpn:
     cap_add:
       - NET_ADMIN
     container_name: vpn_openvpn
     image: kylemanna/openvpn
     ports:
       - "1194:1194/udp"
       - "1194:1194/tcp"
     environment:
      #  - VIRTUAL_PORT=${VIRTUAL_PORT_OPENVPN}
      #  - VIRTUAL_HOST=${VIRTUAL_HOST_OPENVPN}
      #  - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_VPN}
      #  - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      #  - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      #  - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      #  - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      # - LOCAL_NETWORK=192.168.0.0/24
       OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60 -â€“log-driver json-file --log-opt max-size=10m
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
       - ./openvpn_data:/etc/openvpn
     restart: always
     networks:
       vpn-net:
         ipv4_address: 172.110.1.3
     logging:
       driver: "json-file"
       options:
         max-size: "10m"
         max-file: "3"

   pihole:
     image: pihole/pihole
     container_name: vpn_pihole
     cap_add:
       - NET_ADMIN     
     depends_on:
       - openvpn
     ports:
       #- "553:53/tcp"
       #- "553:53/udp"
       - "8081:80/tcp"
     environment:
       WEBPASSWORD: fcvFjLIO2hWhkFCi
       ServerIP: 0.0.0.0
       DNS1: 127.0.0.1
       DNS2: 1.1.1.1
       API_QUERY_LOG_SHOW: blockedonly        # pihole/setupVars.conf
     volumes:
       - ./pihole:/etc/pihole
       - ./pihole_dnsmasq.d:/etc/dnsmasq.d
       - /etc/localtime:/etc/localtime:ro
       - /etc/timezone:/etc/timezone:ro
     restart: always
     networks:
       vpn-net:
         ipv4_address: 172.110.1.4     
     logging:
       driver: "json-file"
       options:
         max-size: "5m"
         max-file: "3"

# docker network create --driver=bridge --subnet=172.110.1.0/24 --gateway=172.110.1.1 vpn-net
networks:
  vpn-net:
    external: true
